language: node_js
node_js:
- '0.10'
deploy:
  provider: heroku
  app: vast-stream-85347
  api_key:
    secure: kfNAis0BrofCEfn0W1UHt9zsDzcPGGygZeXdASgEgvCisQSdjsAtU11df9EN6EIadhuCSpLqYIp4Zw32GB2nMiBF1yKg7h6YigdMsHeVDHMXebEMTzlrTsEPJDlASIEkCsPIiDVIK+gIil0Wl/Uz4zyJj7FOpDXbgTHnagfTmWgAhN125P33xGuBNDQwYwi4Kb9giBul28QPUeaVg38zcMK8frkZMlKOfvmeQ6lFEFp18hCgBnGN5C3Vo8Okl6h6ZIYtLHyiSc92czPPgs5S/eYS5pP+2/X53DnHSiUeeCc+NLkyQvjWsETNiYtyXXIznwJwrQRqrvGmHEnLcFHl5aZZyYub1FLXPQwwxdC8jYlTl/G4r285Z7EE9AZ6X0nGlQDhOnnoejyb4BOAQJgUj2DK3UI66Tq5MWQbC9/f1NWi44FOSExtg6+3WIVNnNkvWWwp1gLpSBlgvTp8YDs5m0y6gABwfQYQ5TeOBup9Tq+w6HGjEWDeLkZsYLuAkCCvuRiG17cwnTSLk4DkVhG3n2drbHHGeiNVavxEwHJHgMVD7wmJLzFoGe33+1Ad9NGD4bgTE44+YUmVUC4aUqj48eo8Sv+siQM0bmXUgStXE+t/yuiWZs0q9ehRvsXUghBV1L8xprq8N4L0xcTPixCXFgnZzHJjZq2g4mgAd1L+H/0=
